openapi: 3.0.0
info:
  title: LangCards API V1 Documentation
  version: 1.0.0
  description: API V1 Documentation
servers:
  - url: http://localhost:8000/api/v1
    description: Version 1.0
paths:
  /registration:
    $ref: "../../api-docs/v1/paths/registration/registration.yaml"
  /login:
    $ref: "../../api-docs/v1/paths/login/login.yaml"
  /auth/{provider}/redirect:
    $ref: "../../api-docs/v1/paths/oauth/oauthRedirect.yaml"
  /auth/{provider}/callback:
    $ref: "../../api-docs/v1/paths/oauth/oauthHandle.yaml"
  /logout:
    $ref: "../../api-docs/v1/paths/logout/logout.yaml"

components:
  schemas:
    registrationRequest:
      $ref: "../../api-docs/v1/schemas/registration/registrationRequest.yaml"
    registrationSuccessResponse:
      $ref: "../../api-docs/v1/schemas/registration/registrationSuccessResponse.yaml"
    validationErrorResponse:
      $ref: "../../api-docs/v1/schemas/registration/validationErrorResponse.yaml"
    authSuccessResponse:
      $ref: "../../api-docs/v1/schemas/login/authSuccessResponse.yaml"
    authUserResource:
      $ref: "../../api-docs/v1/schemas/login/authUserResource.yaml"
    loginRequest:
      $ref: "../../api-docs/v1/schemas/login/loginRequest.yaml"
    loginValidationErrorResponse:
      $ref: "../../api-docs/v1/schemas/login/loginValidationErrorResponse.yaml"
    userNotFoundResponse:
      $ref: "../../api-docs/v1/schemas/login/userNotFoundResponse.yaml"
    notSupportedProviderOAuth:
      $ref: "../../api-docs/v1/schemas/oauth/redirect/notSupportedProviderOAuth.yaml"
    successGetLinkForOAuth:
      $ref: "../../api-docs/v1/schemas/oauth/redirect/successGetLinkForOAuth.yaml"
    authUserResourceOAuthHandle:
      $ref: "../../api-docs/v1/schemas/oauth/handle/authUserResource.yaml"
    existUserWithEmailAndPassword:
      $ref: "../../api-docs/v1/schemas/oauth/handle/existUserWithEmailAndPassword.yaml"
    notSupportedProviderOAuthHandle:
      $ref: "../../api-docs/v1/schemas/oauth/handle/notSupportedProviderOAuth.yaml"
    serverError:
      $ref: "../../api-docs/v1/schemas/oauth/handle/serverError.yaml"
    successAuthorizationOAuth:
      $ref: "../../api-docs/v1/schemas/oauth/handle/successAuthorizationOAuth.yaml"
    accessError:
      $ref: "../../api-docs/v1/schemas/logout/accessError.yaml"
    successLogout:
      $ref: "../../api-docs/v1/schemas/logout/successLogout.yaml"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # Необязательно, чисто информационное поле

